{"level":"ERROR","location":"[get_call:118] fyersModel","message":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /api/v3/profile (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000002493F9F3C10>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))","timestamp":"2024-04-28 13:17:59,601+0530","service":"FyersDataSocket"}
